main:
  - identifier: home
    name: صفحه اصلی
    url: /
    weight: 1
  - identifier: markets
    name: بازارها
    url: /markets/
    weight: 2
  - identifier: banks
    name: موسسات
    url: /banks/
    weight: 3
  - identifier: types
    name: انواع تسهیلات
    url: /types/
    weight: 4
  - identifier: tools
    name: ابزارها
    url: /tools/
    weight: 5
  - identifier: glossary
    name: واژه‌نامه
    url: /glossary/
    weight: 6
  - identifier: contact
    name: تماس با ما
    url: /contact/
    weight: 7
  - identifier: about
    name: درباره
    url: /about/
    weight: 8
